[general]
# Use wl-copy to properly copy images to the Wayland clipboard
copy-command = "wl-copy"

# Exit after copying
early-exit = true

# Actions to perform on copy (Ctrl+C)
action-on-copy = ["save-to-clipboard"]
